# Generated by Django 6.0.3 on 2026-03-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='resumo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Resumo (exibido no card)'),
        ),
    ]
