# Generated by Django 4.2.29 on 2026-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_servico_resumo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='atendente',
            field=models.CharField(choices=[('', 'Selecione...'), ('maria_clara', 'Maria Clara'), ('ketily', 'Ketily')], default='', max_length=20, verbose_name='Atendente'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together={('data', 'hora', 'atendente')},
        ),
    ]
