# Generated by Django 4.2.29 on 2026-03-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_agendamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='agendavel',
            field=models.BooleanField(default=False, verbose_name='Disponível para agendamento'),
        ),
    ]
