# Generated by Django 4.2.29 on 2026-03-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_add_agendavel_to_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Atendente',
                'verbose_name_plural': 'Atendentes',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agendamento.atendente', verbose_name='Atendente'),
        ),
        migrations.CreateModel(
            name='HorarioAtendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira')], verbose_name='Dia da semana')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agendamento.atendente')),
            ],
            options={
                'verbose_name': 'Horário da Atendente',
                'verbose_name_plural': 'Horários das Atendentes',
                'ordering': ['dia_semana', 'hora'],
                'unique_together': {('atendente', 'dia_semana', 'hora')},
            },
        ),
    ]
