# Generated by Django 6.0.3 on 2026-03-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_atendente_alter_agendamento_atendente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_enviado',
            field=models.BooleanField(default=False, verbose_name='Lembrete enviado'),
        ),
    ]
